export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCES';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOSFAILURE';
export const SET_FILTER = 'SET_FILTER';
